import { type Locator, type Page } from '@playwright/test';

/** External Events list, under the CRM module (confirmed against the running app). */
export const EXTERNAL_EVENTS_LIST_PATH = '/crm/events';

/**
 * Raw element locators for "Create External Event" (CRM, Sprint 4 user
 * story) — no actions or assertions here, see
 * src/pages/crm/external-events.page.ts for those.
 *
 * Confirmed against the running app (2026-09-25):
 * - The list screen's entry point is a "Create Event" button (not
 *   "Create External Event") that navigates to its own route
 *   (`/crm/events/new`).
 * - "External Event Date" is a native `<input type="date">` — fill with
 *   an ISO string (e.g. "2026-09-20"), same idiom as every other native
 *   date field already confirmed elsewhere in this app.
 * - "SAITEX Attendees" is a button that opens a popup dialog with a
 *   `listbox` of employee names, not a combobox — selecting one closes
 *   the popup automatically (unlike the Notify Internally multi-select
 *   elsewhere in this app, which needs an explicit dismiss — see
 *   log-communication.page.ts's selectNotifyManager() for that
 *   contrast).
 * - The ClickUp text names only SAITEX Attendees/Score/Number of Leads as
 *   mandatory Feedback Form fields. Confirmed directly this is
 *   incomplete: "What went well?", "What could have been better?", and
 *   "Attend next editions?" are ALSO required — Submit is blocked with
 *   field-level "Required" errors on all three otherwise.
 * - Submit does not save immediately — it opens a confirmation dialog
 *   ("External Event created!", warning that all Managers get notified)
 *   with "Keep editing"/"Save event"; only "Save event" persists it and
 *   redirects to the new event's own Details screen
 *   (`/crm/events/{id}?tab=feedback`).
 *
 * Also covers the List screen (CRM Sprint 3 — "External Events List
 * screen") and the event's own Details/workspace (Sprint 3 — "External
 * Event Details screen"), confirmed 2026-09-25, since both are the same
 * physical route/component as Sprint 4's create flow:
 * - The List's 6 status tabs are: All/Planning/To Attend/Attended shown
 *   directly, with Not Attending/Elapsed tucked behind a "+2 more" menu
 *   button — not all 6 rendered as top-level tabs.
 * - "AI Relevance" (and "Leads") columns exist but are HIDDEN by
 *   default — must be toggled on via "Configure columns" before they can
 *   be sorted on.
 * - CRITICAL: an event only carries the Planning -> To Attend/Not
 *   Attending -> Attended decision lifecycle (decision buttons, AI
 *   dossier sections) when it originates from the AI-discovery pipeline
 *   ("Generated by AI" tag). An event created manually via "Create
 *   Event" (Sprint 4) is saved DIRECTLY as "Attended" — there is no UI
 *   path to create a fresh Planning-stage event. The AI-seeded Planning
 *   pool in this environment is FIXED and NOT replenishable (6 seed
 *   events total, several already elapsed) — tests that consume one
 *   (TC:2 "To Attend", TC:3 "Attended") permanently remove it from the
 *   pool for future runs. See external-events.page.ts's
 *   findFreshPlanningEvent() for how callers should degrade gracefully
 *   once it's exhausted, rather than fail.
 * - A genuinely PAST-or-present-dated event can still show status
 *   "Planning · Elapsed" (a compound status) once its own schedule has
 *   passed — such an event has NO decision buttons at all (nothing left
 *   to decide), unlike a still-upcoming "Planning" event.
 * - The workspace's action buttons (To Attend/Not Attending, or Mark
 *   Attended once "To Attend") sit ABOVE a tab bar of Planning/Feedback
 *   Form/Leads (N) — "Planning" is a FIXED tab label (holds the AI
 *   dossier + decision card), not a live reflection of current status;
 *   Feedback Form/Leads stay disabled until the event reaches Attended.
 * - The decline ("Not Attending") flow is a real modal — "Reason for Not
 *   Attending" (multi-select) + "Detailed Reason" (textbox), both
 *   required, confirmed via real validation errors ("Select at least
 *   one reason" / "Detailed reason is required"). Its confirm button
 *   reads "Proceed", not "Confirm".
 */
export class ExternalEventsLocators {
  readonly createEventButton: Locator;

  // List screen (Sprint 3)
  readonly pageHeading: Locator;
  readonly moreStatusTabsButton: Locator;
  readonly searchInput: Locator;
  readonly configureColumnsButton: Locator;
  readonly columnsDialog: Locator;
  readonly applyColumnsButton: Locator;
  readonly aiRelevanceColumnHeader: Locator;
  readonly emptyStateMessage: Locator;

  // Details/workspace (Sprint 3) — shared with the create flow's own read-back
  readonly toAttendButton: Locator;
  readonly notAttendingButton: Locator;
  readonly markAttendedButton: Locator;
  readonly registerOnlineLink: Locator;
  readonly planningTabButton: Locator;
  readonly feedbackFormTabButton: Locator;
  readonly leadsTabButton: Locator;

  // Decline ("Not Attending") modal
  readonly declineDialog: Locator;
  readonly declineReasonButton: Locator;
  readonly declineDetailedReasonInput: Locator;
  readonly declineProceedButton: Locator;
  readonly declineCancelButton: Locator;

  readonly titleInput: Locator;
  readonly venueInput: Locator;
  readonly dateInput: Locator;
  readonly aboutInput: Locator;

  readonly attendeesButton: Locator;
  readonly scoreRadiogroup: Locator;
  readonly numberOfLeadsInput: Locator;
  readonly wentWellInput: Locator;
  readonly couldBeBetterInput: Locator;
  readonly attendNextEditionsInput: Locator;

  readonly submitButton: Locator;
  readonly cancelButton: Locator;

  readonly confirmDialog: Locator;
  readonly saveEventButton: Locator;
  readonly keepEditingButton: Locator;

  readonly toast: Locator;

  constructor(private readonly page: Page) {
    this.createEventButton = page.getByRole('button', { name: 'Create Event' });

    this.pageHeading = page.getByRole('heading', { name: 'External Events', level: 1 });
    this.moreStatusTabsButton = page.getByRole('button', { name: '+2 more' });
    this.searchInput = page.getByRole('textbox', { name: 'Search' });
    this.configureColumnsButton = page.getByRole('button', { name: 'Configure columns' });
    this.columnsDialog = page.getByRole('dialog', { name: 'Columns' });
    this.applyColumnsButton = this.columnsDialog.getByRole('button', { name: 'Apply' });
    this.aiRelevanceColumnHeader = page.getByRole('button', { name: 'AI Relevance', exact: true });
    this.emptyStateMessage = page.getByText(/no (matching )?(events|records)/i);

    this.toAttendButton = page.getByRole('button', { name: 'To Attend', exact: true });
    this.notAttendingButton = page.getByRole('button', { name: 'Not Attending', exact: true });
    this.markAttendedButton = page.getByRole('button', { name: 'Mark Attended' });
    this.registerOnlineLink = page.getByRole('link', { name: 'Register Online' });
    this.planningTabButton = page.getByRole('button', { name: 'Planning', exact: true });
    this.feedbackFormTabButton = page.getByRole('button', { name: 'Feedback Form', exact: true });
    this.leadsTabButton = page.getByRole('button', { name: /^Leads \(\d+\)$/ });

    this.declineDialog = page.getByRole('dialog', { name: /^Not Attending/ });
    this.declineReasonButton = this.declineDialog.getByRole('button', {
      name: /Select multiple reasons|reason/i,
    });
    this.declineDetailedReasonInput = this.declineDialog.getByRole('textbox');
    this.declineProceedButton = this.declineDialog.getByRole('button', { name: 'Proceed' });
    this.declineCancelButton = this.declineDialog.getByRole('button', { name: 'Cancel', exact: true });

    this.titleInput = page.getByRole('textbox', { name: 'External Event Title', exact: false });
    this.venueInput = page.getByRole('textbox', { name: 'External Event Venue', exact: false });
    this.dateInput = page.getByRole('textbox', { name: 'External Event Date', exact: false });
    this.aboutInput = page.getByRole('textbox', { name: 'About the External Event', exact: false });

    this.attendeesButton = page.getByRole('button', { name: 'SAITEX Attendees' });
    this.scoreRadiogroup = page.getByRole('radiogroup', { name: /Score/ });
    this.numberOfLeadsInput = page.getByRole('textbox', { name: 'Number of Leads', exact: false });
    this.wentWellInput = page.getByRole('textbox', { name: 'What went well?', exact: false });
    this.couldBeBetterInput = page.getByRole('textbox', {
      name: 'What could have been better?',
      exact: false,
    });
    this.attendNextEditionsInput = page.getByRole('textbox', {
      name: 'Attend next editions?',
      exact: false,
    });

    this.submitButton = page.getByRole('button', { name: 'Submit' });
    this.cancelButton = page.getByRole('button', { name: 'Cancel', exact: true });

    this.confirmDialog = page
      .getByRole('dialog')
      .or(page.getByRole('alertdialog'))
      .filter({ hasText: 'External Event created' });
    this.saveEventButton = this.confirmDialog.getByRole('button', { name: 'Save event' });
    this.keepEditingButton = this.confirmDialog.getByRole('button', { name: 'Keep editing' });

    this.toast = page.locator('[data-sonner-toast]').first();
  }

  scoreRadio(value: number): Locator {
    return this.scoreRadiogroup.getByRole('radio', { name: String(value), exact: true });
  }

  attendeeOption(name: string): Locator {
    return this.page.getByRole('option', { name, exact: true });
  }

  /** A status tab button on the List screen, by its bare name (e.g. "Planning") — accessible name carries a live count suffix, e.g. "Planning 5". */
  statusTab(name: string): Locator {
    return this.page.getByRole('button', { name: new RegExp(`^${name} \\d+$`) });
  }

  /** A row in the events table, by its Event title. */
  eventRow(title: string): Locator {
    return this.page.getByRole('row').filter({ hasText: title });
  }

  /** A toggle checkbox in the Configure Columns dialog. */
  columnToggle(columnName: string): Locator {
    return this.columnsDialog.getByRole('checkbox', { name: `Toggle ${columnName}` });
  }

  /** A reason chip option in the decline modal's multi-select (e.g. "Travel constraints"). */
  declineReasonOption(name: string): Locator {
    return this.page.getByRole('option', { name, exact: true });
  }
}
