import * as allure from 'allure-js-commons';
import { test, expect } from '../../../src/fixtures/crm.fixtures';

/**
 * CRM — External Event Details screen (Sprint 3).
 *
 * Source of truth: ClickUp task https://app.clickup.com/t/z941abup9x.
 * Confirmed against the running app (2026-09-25) — see
 * external-events.locators.ts and external-events.page.ts's class docs
 * for the corrections that made.
 *
 * CRITICAL environment constraint, confirmed directly: the Planning ->
 * decision lifecycle this whole story is about only applies to
 * AI-discovered events ("Generated by AI" tag) — an event created
 * manually via "Create Event" (Sprint 4) saves straight to Attended,
 * with no decision to make. This environment's AI-seeded Planning pool
 * is FIXED (a handful of seed events, several already elapsed) and NOT
 * replenishable through the UI. Every real TC here needs a genuinely
 * undecided, NOT-elapsed Planning event — an elapsed one has no decision
 * buttons (no To Attend/Not Attending/Register Online) at all — so ALL
 * of TC:1/2/3/4/5/6/7 go through ExternalEventsPage.findFreshPlanningEvent(),
 * not just the mutating ones. TC:2/TC:3/TC:4 each consume one undecided
 * event permanently by deciding it; TC:1/5/6/7 are non-mutating (opening
 * an event, or a decline flow that ends in Cancel, doesn't change its
 * status) and safely reuse whatever's left. Once the pool is exhausted,
 * every one of them `test.skip()`s with a clear reason rather than fail
 * or hang — same "don't force a false pass/fail on finite, unowned seed
 * data" discipline as biz-doc.spec.ts and qualified-lead-to-prospect.spec.ts.
 * Confirmed directly (2026-09-25) against this environment's pool (3
 * Planning events, 2 already elapsed): running the non-mutating TCs
 * first against the single remaining fresh event, then the mutating
 * ones last, is what actually exercises every TC for real before the
 * pool runs out for good.
 *
 * Also confirmed directly: the Feedback Form/Leads tab buttons are never
 * HTML-disabled (toBeDisabled() always reads false) — locking is
 * enforced by gating their content behind "...opens once this event's
 * status is Attended." text instead, which is what
 * expectFeedbackAndLeadsLocked()/expectFeedbackAndLeadsUnlocked() assert
 * on (external-events.page.ts).
 *
 * TC:8 is `test.fixme()`'d: already marked skip in ClickUp (needs a real
 * date-jump simulation this framework can't do).
 */
test.describe('CRM - External Event Details screen', () => {
  test.beforeEach(async () => {
    await allure.epic('CRM');
    await allure.feature('External Event Details screen');
    await allure.owner('CRM QA');
  });

  test('TC:1 Verification of Initial Tab State for Planning Events', async ({
    externalEventsPage,
  }) => {
    await allure.tms('https://app.clickup.com/t/z941abuqpf', 'TC:1 (ClickUp)');

    // Confirmed against the running app: needs a genuinely undecided,
    // NOT-elapsed Planning event — an already-elapsed one (no pending
    // decision left to make) unlocks Feedback Form/Leads early, which
    // would make this check a false pass. Non-mutating (just opens and
    // reads gate text), so safe to reuse the same fresh event as
    // TC:5/6/7.
    const eventId = await externalEventsPage.findFreshPlanningEvent();
    test.skip(
      eventId === null,
      'No un-elapsed Planning event left in this environment\'s fixed AI-seed pool — see class doc.',
    );

    await test.step('Feedback Form and Leads tabs are gated until Attended', async () => {
      await externalEventsPage.expectFeedbackAndLeadsLocked();
    });
  });

  test('TC:2 Verify Successful Lifecycle Transition to "To Attend"', async ({
    externalEventsPage,
  }) => {
    await allure.tms('https://app.clickup.com/t/z941abuqpg', 'TC:2 (ClickUp)');

    const eventId = await externalEventsPage.findFreshPlanningEvent();
    test.skip(
      eventId === null,
      'No un-elapsed Planning event left in this environment\'s fixed AI-seed pool — see class doc.',
    );

    await test.step('Click To Attend', async () => {
      await externalEventsPage.decideToAttend();
    });

    await test.step('Status updates and the state banner offers Mark Attended', async () => {
      await externalEventsPage.expectStatus('To Attend');
      await expect(externalEventsPage.locators.markAttendedButton).toBeVisible();
    });
  });

  test('TC:3 Verify Transition to "Attended" and Unlocking Restricted Tabs', async ({
    externalEventsPage,
  }) => {
    await allure.tms('https://app.clickup.com/t/z941abuqph', 'TC:3 (ClickUp)');

    const eventId = await externalEventsPage.findFreshPlanningEvent();
    test.skip(
      eventId === null,
      'No un-elapsed Planning event left in this environment\'s fixed AI-seed pool — see class doc.',
    );
    await externalEventsPage.decideToAttend();

    await test.step('Click Mark Attended', async () => {
      await externalEventsPage.markAttended();
    });

    await test.step('Status transitions to Attended and both locked tabs unlock', async () => {
      await externalEventsPage.expectStatus('Attended');
      await externalEventsPage.expectFeedbackAndLeadsUnlocked();
    });
  });

  test('TC:4 verify Submission of Feedback Form and Lead Capture', async ({
    externalEventsPage,
  }) => {
    await allure.tms('https://app.clickup.com/t/z941abuqpj', 'TC:4 (ClickUp)');

    const eventId = await externalEventsPage.findFreshPlanningEvent();
    test.skip(
      eventId === null,
      'No un-elapsed Planning event left in this environment\'s fixed AI-seed pool — see class doc.',
    );
    await externalEventsPage.decideToAttend();
    await externalEventsPage.markAttended();

    await test.step('Fill and submit the Feedback Form', async () => {
      await externalEventsPage.openFeedbackFormTab();
      const l = externalEventsPage.locators;
      await l.attendeesButton.click();
      await l.attendeeOption('Alice Planner').click();
      await l.scoreRadio(8).check();
      await l.numberOfLeadsInput.fill('2');
      await l.wentWellInput.fill('Good turnout.');
      await l.couldBeBetterInput.fill('Nothing major.');
      await l.attendNextEditionsInput.fill('Yes');
      await l.submitButton.click();
    });

    await test.step('Feedback is stored and the Leads tab reflects the capture', async () => {
      await expect(externalEventsPage.locators.toast).toBeVisible();
      // Confirmed against the running app: capturing a lead here hands off
      // to the same Scan&Create/Create Customer flow already owned by
      // scan-create.page.ts/create-customer.page.ts elsewhere in this
      // suite — this test verifies the Feedback Form save and that the
      // Leads tab is reachable, not a second full customer-creation run.
      await externalEventsPage.openLeadsTab();
    });
  });

  test('TC:5 verify External Registration Link Redirection', async ({ externalEventsPage }) => {
    await allure.tms('https://app.clickup.com/t/z941abuqpk', 'TC:5 (ClickUp)');

    // Confirmed against the running app: an already-elapsed Planning
    // event has no Register Online link at all (its decision/registration
    // actions disappear once elapsed) — needs a genuinely fresh one.
    // Non-mutating (just opens a link in a new tab), safe to reuse.
    const eventId = await externalEventsPage.findFreshPlanningEvent();
    test.skip(
      eventId === null,
      'No un-elapsed Planning event left in this environment\'s fixed AI-seed pool — see class doc.',
    );

    await test.step('Clicking Register Online opens the registration URL in a new tab', async () => {
      const newTab = await externalEventsPage.clickRegisterOnlineAndAwaitNewTab();
      expect(newTab, 'expected a new browser tab/window to open for registration').not.toBeNull();
    });
  });

  test('TC:6  Verify Decline Event Validation (Mandatory Reason Check)', async ({
    externalEventsPage,
  }) => {
    await allure.tms('https://app.clickup.com/t/z941abuqpq', 'TC:6 (ClickUp)');

    // Confirmed against the running app: an already-elapsed Planning
    // event has no "Not Attending" button at all (no decision left to
    // make), so this needs a genuinely fresh one. Non-mutating (blocked
    // validation leaves the event in Planning) — safe to reuse.
    const eventId = await externalEventsPage.findFreshPlanningEvent();
    test.skip(
      eventId === null,
      'No un-elapsed Planning event left in this environment\'s fixed AI-seed pool — see class doc.',
    );

    await test.step('Open the decline modal and attempt Proceed with blank fields', async () => {
      await externalEventsPage.openDeclineDialog();
      await externalEventsPage.attemptDeclineWithoutFilling();
    });

    await test.step('Mandatory validation blocks submission', async () => {
      await externalEventsPage.expectFieldError('Select at least one reason');
      await externalEventsPage.expectFieldError('Detailed reason is required');
    });
  });

  test('TC:7  Verify Cancellation of Decline Flow', async ({ externalEventsPage }) => {
    await allure.tms('https://app.clickup.com/t/z941abv3gt', 'TC:7 (ClickUp)');

    // Same as TC:6 — an elapsed Planning event has no "Not Attending"
    // button. Non-mutating by design (this TC's whole point is that
    // Cancel aborts the flow) — safe to reuse.
    const eventId = await externalEventsPage.findFreshPlanningEvent();
    test.skip(
      eventId === null,
      'No un-elapsed Planning event left in this environment\'s fixed AI-seed pool — see class doc.',
    );

    await test.step('Fill a reason and detailed text, then Cancel instead of Proceed', async () => {
      await externalEventsPage.openDeclineDialog();
      await externalEventsPage.fillDeclineReason('Travel constraints', 'Team unavailable to travel this quarter.');
      await externalEventsPage.cancelDecline();
    });

    await test.step('The dialog closes and the event stays in Planning', async () => {
      await expect(externalEventsPage.locators.declineDialog).toBeHidden();
      await externalEventsPage.expectStatus('Planning');
    });
  });

  test('TC:8 verify Automatic Expiration to Elapsed Status', () => {
    test.fixme(
      true,
      'Already marked skip in ClickUp — needs a real server-time jump past an event\'s end date, which this framework cannot simulate.',
    );
  });
});
